fail if dataset is not downloaded and enabled tests on publication

diff --git a/.github/workflows/PUBLICATION.yaml b/.github/workflows/PUBLICATION.yaml
--- a/.github/workflows/PUBLICATION.yaml
+++ b/.github/workflows/PUBLICATION.yaml
@@ -30,23 +30,27 @@ jobs:
       - name: Build
         run: cmake --build ${{github.workspace}}/build -j 16
 
+      - name: Test
+        working-directory: ${{github.workspace}}/build
+        run: ctest -j 4
+
       - name: Check if ALP_DATASET_DIR_PATH is set and print download link
         run: |
           if [ -z "${ALP_DATASET_DIR_PATH}" ]; then
             echo -e "\033[33mPlease download the dataset from: https://drive.google.com/drive/folders/167faTwZJjqJMKM9Yc6E7KF5LUbsitxJS?usp=sharing\033[0m"
             echo -e "\033[33mWarning: ALP_DATASET_DIR_PATH is not set!\033[0m"
+            exit 1  # Fail the workflow
           else
             echo "ALP_DATASET_DIR_PATH is set to ${ALP_DATASET_DIR_PATH}"
           fi
 
-
-      - name: run alp
+      - name: run compression ratio alp
         run: ${{github.workspace}}/build/b/publication/source_code/bench_compression_ratio/bench_alp_compression_ratio
 
-      - name: run alp32
+      - name: run compression ratio alp32
         run: ${{github.workspace}}/build/b/publication/source_code/bench_compression_ratio/bench_alp32_compression_ratio
 
-      - name: run zstd
+      - name: run compression ratio zstd
         run: ${{github.workspace}}/build/b/publication/source_code/bench_compression_ratio/bench_zstd_compression_ratio
       - name: run bench_alp_cutter_decode
         run: ${{github.workspace}}/build/b/publication/source_code/bench/bench_alp_cutter_decode
